/**
 * PiRpcManager — Maps session IDs to PiProcess instances.
 *
 * Responsibilities:
 * - Create sessions → spawn PiProcess with given options
 * - Look up sessions by ID
 * - Stop individual sessions → kill PiProcess
 * - Stop all sessions (server shutdown)
 * - Handle Pi process crash/exit → clean up session, emit events, log stderr
 *
 * One Pi RPC process per session. The manager owns the lifecycle of all
 * processes and ensures cleanup on crash or intentional shutdown.
 *
 * @see docs/PI_INTEGRATION.md — Pi RPC protocol reference
 * @see apps/server/src/piProcess.ts — Individual process wrapper
 */

import { PiProcess, type PiProcessOptions } from "./piProcess.js";

// ============================================================================
// Types
// ============================================================================

/** Information about a managed session. */
export interface ManagedSession {
	/** Unique session ID (generated by PiRpcManager). */
	id: string;
	/** The underlying PiProcess instance. */
	process: PiProcess;
	/** When this session was created. */
	createdAt: number;
}

/** Callback for session lifecycle events. */
export type SessionEventListener = (sessionId: string, event: SessionEvent) => void;

/** Events emitted by the manager about session lifecycle. */
export type SessionEvent =
	| { type: "created" }
	| { type: "stopped" }
	| { type: "crashed"; exitCode: number; stderr: string };

/** Options for creating a new session. */
export interface CreateSessionOptions extends PiProcessOptions {
	/** Custom session ID. If not provided, one is generated. */
	sessionId?: string;
}

/** Options for PiRpcManager constructor. */
export interface PiRpcManagerOptions {
	/** Default piCommand for all sessions (overridable per-session). */
	defaultPiCommand?: string;
}

// ============================================================================
// PiRpcManager
// ============================================================================

export class PiRpcManager {
	private sessions = new Map<string, ManagedSession>();
	private sessionListeners: SessionEventListener[] = [];
	private sessionCounter = 0;
	private readonly defaultPiCommand: string | undefined;

	/** Unsubscribe functions for PiProcess listeners, keyed by session ID. */
	private cleanupFns = new Map<string, (() => void)[]>();

	constructor(options?: PiRpcManagerOptions) {
		this.defaultPiCommand = options?.defaultPiCommand;
	}

	// =========================================================================
	// Session Lifecycle
	// =========================================================================

	/**
	 * Create a new session and spawn a PiProcess.
	 *
	 * @returns The session ID and the PiProcess instance.
	 * @throws If a session with the given custom ID already exists.
	 */
	createSession(options: CreateSessionOptions = {}): ManagedSession {
		const { sessionId: customId, ...processOptions } = options;
		const id = customId ?? this.generateId();

		if (this.sessions.has(id)) {
			throw new Error(`Session '${id}' already exists`);
		}

		// Apply default piCommand if not specified per-session
		const resolvedOptions = {
			...processOptions,
			...(this.defaultPiCommand &&
				!processOptions.piCommand && { piCommand: this.defaultPiCommand }),
		};

		const piProcess = new PiProcess(resolvedOptions);

		// Wire up crash/exit handling BEFORE starting the process
		const cleanups = this.attachProcessListeners(id, piProcess);
		this.cleanupFns.set(id, cleanups);

		// Start the process
		piProcess.start();

		const session: ManagedSession = {
			id,
			process: piProcess,
			createdAt: Date.now(),
		};

		this.sessions.set(id, session);

		this.emitSessionEvent(id, { type: "created" });

		return session;
	}

	/**
	 * Get a session by ID.
	 *
	 * @returns The managed session, or undefined if not found.
	 */
	getSession(sessionId: string): ManagedSession | undefined {
		return this.sessions.get(sessionId);
	}

	/**
	 * Get all active sessions.
	 *
	 * Only returns sessions whose process is in "running" state.
	 */
	getActiveSessions(): ManagedSession[] {
		const active: ManagedSession[] = [];
		for (const session of this.sessions.values()) {
			if (session.process.state === "running") {
				active.push(session);
			}
		}
		return active;
	}

	/**
	 * Get all sessions (including stopped/crashed).
	 */
	getAllSessions(): ManagedSession[] {
		return [...this.sessions.values()];
	}

	/**
	 * Check whether a session exists (any state).
	 */
	hasSession(sessionId: string): boolean {
		return this.sessions.has(sessionId);
	}

	/**
	 * Stop a single session and clean up.
	 *
	 * Gracefully stops the PiProcess (SIGTERM → timeout → SIGKILL).
	 * Removes the session from the manager. Safe to call if already
	 * stopped or if the session doesn't exist.
	 */
	async stopSession(sessionId: string): Promise<void> {
		const session = this.sessions.get(sessionId);
		if (!session) return;

		// Remove from manager first to prevent re-entrant cleanup from onExit
		this.removeSession(sessionId);

		// Stop the process (handles already-stopped gracefully)
		await session.process.stop();

		this.emitSessionEvent(sessionId, { type: "stopped" });
	}

	/**
	 * Stop all sessions.
	 *
	 * Stops all sessions in parallel. Used during server shutdown.
	 * Waits for all processes to exit.
	 */
	async stopAll(): Promise<void> {
		const sessionIds = [...this.sessions.keys()];
		await Promise.all(sessionIds.map((id) => this.stopSession(id)));
	}

	/**
	 * Number of sessions (all states).
	 */
	get size(): number {
		return this.sessions.size;
	}

	// =========================================================================
	// Listeners
	// =========================================================================

	/**
	 * Subscribe to session lifecycle events (created, stopped, crashed).
	 *
	 * @returns Unsubscribe function.
	 */
	onSessionEvent(listener: SessionEventListener): () => void {
		this.sessionListeners.push(listener);
		return () => {
			const index = this.sessionListeners.indexOf(listener);
			if (index !== -1) {
				this.sessionListeners.splice(index, 1);
			}
		};
	}

	// =========================================================================
	// Internal: Process Listener Wiring
	// =========================================================================

	/**
	 * Attach exit and error listeners to a PiProcess for crash handling.
	 *
	 * When a PiProcess exits unexpectedly (state becomes "crashed"):
	 * - Emit a "crashed" session event with exit code and captured stderr
	 * - Remove the session from the manager
	 * - Clean up all listener subscriptions
	 *
	 * When a PiProcess exits expectedly (state is "stopped"):
	 * - No action needed — stopSession() already handled cleanup
	 *
	 * @returns Array of unsubscribe functions for cleanup.
	 */
	private attachProcessListeners(sessionId: string, process: PiProcess): (() => void)[] {
		const cleanups: (() => void)[] = [];

		const unsubExit = process.onExit((code: number) => {
			this.handleProcessExit(sessionId, process, code);
		});
		cleanups.push(unsubExit);

		const unsubError = process.onError((error: Error) => {
			this.handleProcessError(sessionId, error);
		});
		cleanups.push(unsubError);

		return cleanups;
	}

	/**
	 * Handle a PiProcess exit event.
	 *
	 * If the process state is "crashed" (unexpected exit), emit a session
	 * crash event and clean up. If "stopped" (expected), no action —
	 * stopSession() already handled it.
	 */
	private handleProcessExit(sessionId: string, process: PiProcess, code: number): void {
		// Only act on unexpected exits (crash). Expected exits are handled by stopSession().
		if (process.state !== "crashed") return;

		// Still in our session map? Clean it up.
		if (this.sessions.has(sessionId)) {
			const stderr = process.stderr;
			this.removeSession(sessionId);

			this.emitSessionEvent(sessionId, {
				type: "crashed",
				exitCode: code,
				stderr,
			});
		}
	}

	/**
	 * Handle a PiProcess-level error (JSONL parse failure, stream error).
	 *
	 * These are non-fatal — the process may still be running. Log for debugging
	 * but don't remove the session. Fatal errors cause the process to exit,
	 * which handleProcessExit will catch.
	 */
	private handleProcessError(_sessionId: string, _error: Error): void {
		// Process-level errors (parse failures, stream errors) are non-fatal.
		// The PiProcess itself logs these via its error listeners.
		// Consumers who need to react should subscribe to the PiProcess's
		// onError directly (obtained from the ManagedSession).
		//
		// In the future, we could emit a session warning event here,
		// but for now the PiProcess's own error listener chain is sufficient.
	}

	// =========================================================================
	// Internal: Cleanup & Helpers
	// =========================================================================

	/**
	 * Remove a session from the manager and clean up its listener subscriptions.
	 */
	private removeSession(sessionId: string): void {
		this.sessions.delete(sessionId);

		// Unsubscribe from PiProcess listeners
		const cleanups = this.cleanupFns.get(sessionId);
		if (cleanups) {
			for (const unsub of cleanups) {
				unsub();
			}
			this.cleanupFns.delete(sessionId);
		}
	}

	/** Generate a unique session ID. */
	private generateId(): string {
		return `session_${++this.sessionCounter}_${Date.now()}`;
	}

	/** Emit a session event to all listeners. */
	private emitSessionEvent(sessionId: string, event: SessionEvent): void {
		for (const listener of this.sessionListeners) {
			listener(sessionId, event);
		}
	}
}
