/**
 * @pibun/contracts — Shared TypeScript types (no runtime logic)
 *
 * Re-exports all type definitions for Pi RPC protocol and WebSocket protocol.
 * This package has ZERO runtime code — only interfaces, types, type aliases,
 * and const value objects (method/channel name maps).
 */

// Pi RPC protocol types (base types, events, commands, responses — all in one file)
export type {
	// Base types: content blocks
	PiTextContent,
	PiThinkingContent,
	PiImageContent,
	PiToolCall,
	// Base types: usage, enums
	PiUsage,
	PiStopReason,
	PiThinkingLevel,
	PiSteeringMode,
	PiFollowUpMode,
	// Base types: messages
	PiUserMessage,
	PiAssistantMessage,
	PiToolResultMessage,
	PiBashExecutionMessage,
	PiAgentMessage,
	// Base types: model, results, state
	PiModel,
	PiAssistantMessageEvent,
	PiToolResult,
	PiCompactionResult,
	PiSessionStats,
	PiBashResult,
	PiSessionState,
	PiSlashCommand,
	// Events: agent lifecycle
	PiAgentStartEvent,
	PiAgentEndEvent,
	// Events: turn lifecycle
	PiTurnStartEvent,
	PiTurnEndEvent,
	// Events: message lifecycle
	PiMessageStartEvent,
	PiMessageUpdateEvent,
	PiMessageEndEvent,
	// Events: tool execution
	PiToolExecutionStartEvent,
	PiToolExecutionUpdateEvent,
	PiToolExecutionEndEvent,
	// Events: auto-recovery
	PiAutoCompactionStartEvent,
	PiAutoCompactionEndEvent,
	PiAutoRetryStartEvent,
	PiAutoRetryEndEvent,
	// Events: extension
	PiExtensionErrorEvent,
	PiExtensionSelectRequest,
	PiExtensionConfirmRequest,
	PiExtensionInputRequest,
	PiExtensionEditorRequest,
	PiExtensionNotifyRequest,
	PiExtensionSetStatusRequest,
	PiExtensionSetWidgetRequest,
	PiExtensionSetTitleRequest,
	PiExtensionSetEditorTextRequest,
	PiExtensionDialogRequest,
	PiExtensionFireAndForgetRequest,
	PiExtensionUIRequest,
	PiEvent,
	// Commands
	PiPromptCommand,
	PiSteerCommand,
	PiFollowUpCommand,
	PiAbortCommand,
	PiNewSessionCommand,
	PiGetStateCommand,
	PiGetMessagesCommand,
	PiSetModelCommand,
	PiCycleModelCommand,
	PiGetAvailableModelsCommand,
	PiSetThinkingLevelCommand,
	PiCycleThinkingLevelCommand,
	PiSetSteeringModeCommand,
	PiSetFollowUpModeCommand,
	PiCompactCommand,
	PiSetAutoCompactionCommand,
	PiSetAutoRetryCommand,
	PiAbortRetryCommand,
	PiBashCommand,
	PiAbortBashCommand,
	PiGetSessionStatsCommand,
	PiExportHtmlCommand,
	PiSwitchSessionCommand,
	PiForkCommand,
	PiGetForkMessagesCommand,
	PiGetLastAssistantTextCommand,
	PiSetSessionNameCommand,
	PiGetCommandsCommand,
	PiCommand,
	PiCommandType,
	// Commands: extension UI responses
	PiExtensionUIValueResponse,
	PiExtensionUIConfirmResponse,
	PiExtensionUICancelResponse,
	PiExtensionUIResponse,
	// Responses
	PiPromptResponse,
	PiSteerResponse,
	PiFollowUpResponse,
	PiAbortResponse,
	PiNewSessionResponse,
	PiGetStateResponse,
	PiGetMessagesResponse,
	PiSetModelResponse,
	PiCycleModelResponse,
	PiGetAvailableModelsResponse,
	PiSetThinkingLevelResponse,
	PiCycleThinkingLevelResponse,
	PiSetSteeringModeResponse,
	PiSetFollowUpModeResponse,
	PiCompactResponse,
	PiSetAutoCompactionResponse,
	PiSetAutoRetryResponse,
	PiAbortRetryResponse,
	PiBashResponse,
	PiAbortBashResponse,
	PiGetSessionStatsResponse,
	PiExportHtmlResponse,
	PiSwitchSessionResponse,
	PiForkResponse,
	PiGetForkMessagesResponse,
	PiGetLastAssistantTextResponse,
	PiSetSessionNameResponse,
	PiGetCommandsResponse,
	PiErrorResponse,
	PiResponse,
	PiStdoutLine,
} from "./piProtocol.js";

// Session tab types (multi-session UI)
export type { SessionTab } from "./sessionTab.js";

// Project types (project management)
export type { Project, ProjectModelPreference } from "./project.js";

// Theme types (custom theming system)
export type { Theme, ThemeColors, ThemeId, ThemePreference } from "./theme.js";

// Settings types (application preferences)
export type { PiBunSettings } from "./settings.js";

// Plugin types (plugin system)
export type {
	PiBunEventMessage,
	PiBunSessionStateMessage,
	PiBunThemeChangedMessage,
	PiBunToPluginMessage,
	Plugin,
	PluginGetSessionStateMessage,
	PluginManifest,
	PluginPanelConfig,
	PluginPanelPosition,
	PluginReadyMessage,
	PluginSendPromptMessage,
	PluginSubscribeEventsMessage,
	PluginToPiBunMessage,
	PluginUnsubscribeEventsMessage,
} from "./plugin.js";

// Git types (git integration)
export type {
	GitChangedFile,
	GitDiffResult,
	GitLogEntry,
	GitLogResult,
	GitStatusResult,
} from "./gitTypes.js";

// WebSocket protocol types (browser ↔ server)
export { WS_CHANNELS, WS_METHODS } from "./wsProtocol.js";
export type {
	WsChannel,
	WsChannelDataMap,
	WsImageAttachment,
	WsMethod,
	WsMethodParamsMap,
	WsMethodResultMap,
	WsOkResult,
	WsPush,
	WsRequest,
	WsResponse,
	WsResponseError,
	WsResponseOk,
	WsAppUpdateData,
	WsMenuActionData,
	WsPiEventData,
	WsPiResponseData,
	WsServerErrorData,
	WsServerMessage,
	WsServerWelcomeData,
	WsSessionCompactParams,
	WsSessionExtensionUiResponseParams,
	WsSessionFollowUpParams,
	WsForkableMessage,
	WsSessionForkParams,
	WsSessionForkResult,
	WsSessionGetForkMessagesResult,
	WsSessionGetMessagesResult,
	WsSessionGetModelsResult,
	WsSessionGetStateResult,
	WsSessionGetStatsResult,
	WsSessionNewResult,
	WsSessionPromptParams,
	WsSessionSetModelParams,
	WsSessionSetNameParams,
	WsSessionSetThinkingParams,
	WsSessionStartParams,
	WsSessionStartResult,
	WsSessionSteerParams,
	WsSessionExportHtmlParams,
	WsSessionExportHtmlResult,
	WsSessionListSessionsResult,
	WsSessionSummary,
	WsSessionSwitchSessionParams,
	WsSessionSwitchSessionResult,
	WsAppOpenFolderDialogResult,
	WsAppSaveExportFileParams,
	WsAppSaveExportFileResult,
	WsAppSetWindowTitleParams,
	WsTerminalCloseParams,
	WsTerminalCreateParams,
	WsTerminalCreateResult,
	WsTerminalDataPush,
	WsTerminalExitPush,
	WsTerminalResizeParams,
	WsTerminalWriteParams,
	WsGitBranchParams,
	WsGitBranchResult,
	WsGitDiffParams,
	WsGitDiffResult,
	WsGitLogParams,
	WsGitLogResult,
	WsGitStatusParams,
	WsGitStatusResult,
	WsProjectAddParams,
	WsProjectAddResult,
	WsProjectListResult,
	WsProjectRemoveParams,
	WsProjectUpdateParams,
	WsSettingsGetResult,
	WsSettingsUpdateParams,
	WsSettingsUpdateResult,
	WsPluginInstallParams,
	WsPluginInstallResult,
	WsPluginListResult,
	WsPluginSetEnabledParams,
	WsPluginUninstallParams,
	WsTypedPush,
	WsTypedRequest,
	WsTypedResponse,
	WsTypedResponseOk,
	AppUpdateStatus,
} from "./wsProtocol.js";
