/**
 * @pibun/contracts — Shared TypeScript types (no runtime logic)
 *
 * Re-exports all type definitions for Pi RPC protocol and WebSocket protocol.
 * This package has ZERO runtime code — only interfaces, types, type aliases,
 * and const value objects (method/channel name maps).
 */

// Base Pi types (content blocks, messages, model, etc.)
export type {
	PiAgentMessage,
	PiAssistantMessage,
	PiAssistantMessageEvent,
	PiBashExecutionMessage,
	PiBashResult,
	PiCompactionResult,
	PiFollowUpMode,
	PiImageContent,
	PiModel,
	PiSessionState,
	PiSessionStats,
	PiSlashCommand,
	PiSteeringMode,
	PiStopReason,
	PiTextContent,
	PiThinkingContent,
	PiThinkingLevel,
	PiToolCall,
	PiToolResult,
	PiToolResultMessage,
	PiUsage,
	PiUserMessage,
} from "./piTypes.js";

// Pi RPC event types (stdout)
export type {
	PiAgentEndEvent,
	PiAgentStartEvent,
	PiAutoCompactionEndEvent,
	PiAutoCompactionStartEvent,
	PiAutoRetryEndEvent,
	PiAutoRetryStartEvent,
	PiEvent,
	PiExtensionConfirmRequest,
	PiExtensionDialogRequest,
	PiExtensionEditorRequest,
	PiExtensionErrorEvent,
	PiExtensionFireAndForgetRequest,
	PiExtensionInputRequest,
	PiExtensionNotifyRequest,
	PiExtensionSelectRequest,
	PiExtensionSetEditorTextRequest,
	PiExtensionSetStatusRequest,
	PiExtensionSetTitleRequest,
	PiExtensionSetWidgetRequest,
	PiExtensionUIRequest,
	PiMessageEndEvent,
	PiMessageStartEvent,
	PiMessageUpdateEvent,
	PiToolExecutionEndEvent,
	PiToolExecutionStartEvent,
	PiToolExecutionUpdateEvent,
	PiTurnEndEvent,
	PiTurnStartEvent,
} from "./piEvents.js";

// Pi RPC command types (stdin)
export type {
	PiAbortBashCommand,
	PiAbortCommand,
	PiBashCommand,
	PiCommand,
	PiCommandType,
	PiCompactCommand,
	PiCycleModelCommand,
	PiCycleThinkingLevelCommand,
	PiExportHtmlCommand,
	PiExtensionUICancelResponse,
	PiExtensionUIConfirmResponse,
	PiExtensionUIResponse,
	PiExtensionUIValueResponse,
	PiFollowUpCommand,
	PiForkCommand,
	PiGetAvailableModelsCommand,
	PiGetCommandsCommand,
	PiGetForkMessagesCommand,
	PiGetLastAssistantTextCommand,
	PiGetMessagesCommand,
	PiGetSessionStatsCommand,
	PiGetStateCommand,
	PiNewSessionCommand,
	PiPromptCommand,
	PiSetAutoCompactionCommand,
	PiSetAutoRetryCommand,
	PiSetFollowUpModeCommand,
	PiSetModelCommand,
	PiSetSessionNameCommand,
	PiSetSteeringModeCommand,
	PiSetThinkingLevelCommand,
	PiSteerCommand,
	PiSwitchSessionCommand,
} from "./piCommands.js";

// Pi RPC response types (stdout)
export type {
	PiAbortBashResponse,
	PiAbortResponse,
	PiAbortRetryResponse,
	PiBashResponse,
	PiCompactResponse,
	PiCycleModelResponse,
	PiCycleThinkingLevelResponse,
	PiErrorResponse,
	PiExportHtmlResponse,
	PiFollowUpResponse,
	PiForkResponse,
	PiGetAvailableModelsResponse,
	PiGetCommandsResponse,
	PiGetForkMessagesResponse,
	PiGetLastAssistantTextResponse,
	PiGetMessagesResponse,
	PiGetSessionStatsResponse,
	PiGetStateResponse,
	PiNewSessionResponse,
	PiPromptResponse,
	PiResponse,
	PiSetAutoCompactionResponse,
	PiSetAutoRetryResponse,
	PiSetFollowUpModeResponse,
	PiSetModelResponse,
	PiSetSessionNameResponse,
	PiSetSteeringModeResponse,
	PiSetThinkingLevelResponse,
	PiStdoutLine,
	PiSteerResponse,
	PiSwitchSessionResponse,
} from "./piResponses.js";

// Session tab types (multi-session UI)
export type { SessionTab } from "./sessionTab.js";

// Project types (project management)
export type { Project, ProjectModelPreference } from "./project.js";

// WebSocket protocol types (browser ↔ server)
export { WS_CHANNELS, WS_METHODS } from "./wsProtocol.js";
export type {
	WsChannel,
	WsChannelDataMap,
	WsImageAttachment,
	WsMethod,
	WsMethodParamsMap,
	WsMethodResultMap,
	WsOkResult,
	WsPush,
	WsRequest,
	WsResponse,
	WsResponseError,
	WsResponseOk,
	WsAppUpdateData,
	WsMenuActionData,
	WsPiEventData,
	WsPiResponseData,
	WsServerErrorData,
	WsServerMessage,
	WsServerWelcomeData,
	WsSessionCompactParams,
	WsSessionExtensionUiResponseParams,
	WsSessionFollowUpParams,
	WsForkableMessage,
	WsSessionForkParams,
	WsSessionForkResult,
	WsSessionGetForkMessagesResult,
	WsSessionGetMessagesResult,
	WsSessionGetModelsResult,
	WsSessionGetStateResult,
	WsSessionGetStatsResult,
	WsSessionNewResult,
	WsSessionPromptParams,
	WsSessionSetModelParams,
	WsSessionSetNameParams,
	WsSessionSetThinkingParams,
	WsSessionStartParams,
	WsSessionStartResult,
	WsSessionSteerParams,
	WsSessionListSessionsResult,
	WsSessionSummary,
	WsSessionSwitchSessionParams,
	WsSessionSwitchSessionResult,
	WsProjectAddParams,
	WsProjectAddResult,
	WsProjectListResult,
	WsProjectRemoveParams,
	WsProjectUpdateParams,
	WsTypedPush,
	WsTypedRequest,
	WsTypedResponse,
	WsTypedResponseOk,
	AppUpdateStatus,
} from "./wsProtocol.js";
